### ISSUE TITLE
登陆的时候又报错啦F12

### ISSUE THREAD

**Issue by kanongbz** [piexlmax/gin-vue-admin#12]
Property or method "handleClose" is not defined on the instance but referenced during render.

**Comment by krank666** [comment]
这是一个[vue warn]，我们马上处理！

**Comment by krank666** [comment]
> Property or method "handleClose" is not defined on the instance but referenced during render.
已解决嗷，请更新代码

**Comment by kanongbz** [comment]
好的好的 谢谢
