### ISSUE TITLE
项目包引入问题

### ISSUE THREAD

**Issue by UncleChJJ** [piexlmax/gin-vue-admin#18]
![image](https://user-images.githubusercontent.com/35246151/71974311-26517f80-324c-11ea-9165-69abe61f9fce.png)
这个项目包引入不对吧，不应该是下边这样的吗？
![image](https://user-images.githubusercontent.com/35246151/71974345-42552100-324c-11ea-8167-85e28f87ee33.png)

**Comment by piexlmax** [comment]
是这样的 这个项目的后端资源和前端是分离的 server为后端资源 所以mod所在地址为server这个文件夹内部，因此不需要再去携带/QMPlusServer这个包路径了，如果把mod放置到最外层文件下，就需要这样去写了。关键还是看配置
