### ISSUE TITLE
招聘岗位（android，ios，前端，测试，产品，UI，运维，PHP）

### ISSUE THREAD

**Issue by jifengkejihr** [piexlmax/gin-vue-admin#20]
菲律宾马尼拉上班，电子游戏棋牌游戏开发，
正规持牌集团，纯开发团队（开发团队规模80人+）
高薪，高福利，安全可靠

欢迎咨询，欢迎咨询，欢迎咨询
Email: jifenghr@gmail.com
QQ: 3292067300
Wechat：sing22028
Tegegram：peterparkzhang

详细见链接
https://github.com/jifengkejihr/jd

**Comment by piexlmax** [comment]
请勿相信此类广告，会失去人身自由。
