### ISSUE TITLE
api管理条件查询，分页显示，统计显示错误，显示34条。

### ISSUE THREAD

**Issue by Finishtime** [piexlmax/gin-vue-admin#21]
![Screenshot from 2020-02-02 15-56-00](https://user-images.githubusercontent.com/46260865/73605070-9d243300-45d4-11ea-8d83-4412be6d3f8c.png)

**Comment by Finishtime** [comment]
条件查询符合条件只有一条，应该显示共1条，也只应该显示1页。

**Comment by piexlmax** [comment]
> 条件查询符合条件只有一条，应该显示共1条，也只应该显示1页。

感谢提出BUG，此问题是由于条件分页的总条数和当时设计的分页存在一定逻辑差别，暂时已经用最简单的方法修复，正在寻找更加合适的方法，拉代码即可解决，感谢。
