### ISSUE TITLE
角色权限管理

### ISSUE THREAD

**Issue by Kotodian** [piexlmax/gin-vue-admin#28]
点击设置权限就一直在加载,好像是内存溢出了。

**Comment by piexlmax** [comment]
> 点击设置权限就一直在加载,好像是内存溢出了。

请使用新版 旧版本未做限制  可以传入空信息 空信息导致递归方法死循环 内存溢出 现在已修复

**Comment by Kotodian** [comment]
是前端的问题吗

**Comment by piexlmax** [comment]
> 是前端的问题吗

是的 前端未做限制 当角色id为空或者0的时候会去找parentID为0的角色 此时他自己就是0 因此进入死循环 现在前端增加了校验 即可避免 后端 请使用ShouldBindJSON进行数据绑定 否则存在未知情况导致数据绑定到结构体为空

**Comment by Kotodian** [comment]
新版我下了。。还是不行

**Comment by Kotodian** [comment]
新版的也还是不行。。。

**Comment by piexlmax** [comment]
> 新版的也还是不行。。。

可以添加我的微信  shouzi_1994 我远程看一下bug 然后修复
