### ISSUE TITLE
为什么基本都是POST

### ISSUE THREAD

**Issue by zou2699** [piexlmax/gin-vue-admin#38]
您好，我粗略看了下api，发现method基本都是POST，请问是基于什么考量的呢，后续会考虑RESTful吗？

**Comment by piexlmax** [comment]
> 您好，我粗略看了下api，发现method基本都是POST，请问是基于什么考量的呢，后续会考虑RESTful吗？

当前是支持RESTful的，开始个人开发习惯将其全定制为了POST，2.0版本已经提上日程，更规范可用性更高
