### ISSUE TITLE
录入模板、查询模板、强大的grid表格示例

### ISSUE THREAD

**Issue by chmis8000** [piexlmax/gin-vue-admin#5]
大量现实做项目， 能快速做 查询界面、录入+修改界面。
另外，强大的grid表格示例很重要。
我从net转来，参考fineui 开源框架示例： https://pro.fineui.com/

**Comment by piexlmax** [comment]
前端ui框架使用的element-ui作为基础 这些功能是有的 我会把element-ui 添加进入readme 感谢
