### ISSUE TITLE
请问你封装的这个分页如果要进行条件查询的话要怎么实现

### ISSUE THREAD

**Issue by a190992** [piexlmax/gin-vue-admin#6]

**Comment by kanongbz** [comment]
我也有条件筛选这个问题

**Comment by piexlmax** [comment]
每个分页器都需要实现GetInfoList方法 初期设计没有增加条件查找 GetInfoList 方法可以自行改造 增加不定项参数 例如修改为 GetInfoList（info modelInterface.PageInfo,v ...string） 从而将条件传入 我会尽快增加条件查询功能 如果急用可以自行修改 欢迎pr

**Comment by piexlmax** [comment]
忘记说明 方法内部 db 为 返回的*gorm.DB 可以对db进行 order排序 where条件 等等链式操作 参数传入以后即可自行编写 参考 api内部的 order排序
