### ISSUE TITLE
更新之后 登陆会 vuex.esm.js:657 [vuex] unknown local action type: SetAsyncRouter, global type: user/SetAsyncRouter

### ISSUE THREAD

**Issue by kanongbz** [piexlmax/gin-vue-admin#8]
点击登录，vuex.esm.js:657 [vuex] unknown local action type: SetAsyncRouter, global type: user/SetAsyncRouter
但是能登陆，功能也没影响，不知道你们有这个问题不
另外很好用，很感谢

**Comment by piexlmax** [comment]
问题已修复 原因是 vuex内防止白屏代码忘记增加 root:true属性 导致调用了本model中的方法 从而出现方法缺失 感谢指出bug

**Comment by kanongbz** [comment]
哈哈，好的。很好用 真的很好用

**Comment by kanongbz** [comment]
谢谢
